openapi: 3.0.0
info:
  title: Quizin API
  description: >
    An API for simple Quiz Application. This documentation lists the operations supported by this 
    API. Some operations needs a JWT token that is obtainable from successful authentication. These 
    operations are marked by padlock icon on the right. Don't forget to add it! [Last update:24-05-03]
  version: 0.1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /:
    get:
      tags:
        - app
      summary: API's landing page
      description: Displays a message to tell that this server is good to go
      responses:
        '200':    # status code
          description: A simple message
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                      example: Welcome to Quizin!

  /api-docs:
    get:
      tags:
        - app
      summary: API's documentation page
      description: Displays documentation of the API
      responses:
        '200':    # status code
          description: >
            Displays documentation of the API such as what the parameters or request body 
            the server expects you to send
          content: text/html

  /app/leaderboard/{quizId}:
      get:
        tags:
          - app
        summary: Displays the best attempts of a Quiz ranked from the best.
        description: >
          Displays the best attempts on Quiz with id of `quizId`.  Only 
          the user's best attempt is considered during leaderboard generation.
        parameters:
          - in: path
            name: quizId
            type: integer
            required: true
            description: The id of the existing Quiz
        responses:
          '200':
            description: Leaderboard for the quiz successfully fetched
            content:
              application/json:
                schema:
                    type: object
                    properties:
                      msg: 
                        type: string
                      data: 
                        type: integer
                example: 
                  msg: "Best attempt fetch success"
                  data: [
                    {
                      id: 12,
                      user_id: 12,
                      quiz_id: 6,
                      score: 10,
                      username: jojon5,
                      name: jojon5,
                      password: "~",
                      role: "~",
                    },
                    {
                      id: 13,
                      user_id: 13,
                      quiz_id: 6,
                      score: 10,
                      username: jeremy6,
                      name: Jeremy,
                      password: "~",
                      role: "~",
                    }
                  ]


  /app/dashboard:
      get:
        tags:
          - app
        summary: Displays nonprofile informations about user
        description: >
          Displays informations such as quiz that has been done by user along
          with its simple statistics
        security:
          - bearerAuth: []
        responses:
          '200':
            description: Leaderboard for the quiz successfully fetched
            content:
              application/json:
                schema:
                    type: object
                    properties:
                      msg: 
                        type: string
                      data: 
                        type: array
                example: 
                  msg: "Best attempt fetch success"
                  data: [
                    {
                      id: 12,
                      user_id: 12,
                      quiz_id: 6,
                      score: 10,
                      username: jojon5,
                      name: jojon5,
                      password: "~",
                      role: "~",
                    },
                    {
                      id: 13,
                      user_id: 13,
                      quiz_id: 6,
                      score: 10,
                      username: jeremy6,
                      name: Jeremy,
                      password: "~",
                      role: "~",
                    }
                  ]


  /app/profile:
      get:
        tags:
          - app
        summary: Displays the profile of logged user
        description: >
          Displays the logged user's information A valid JWT token is needed
        security:
          - bearerAuth: []
        responses:
          '200':
            description: Information of logged user
            content:
              application/json:
                schema:
                    type: object
                    properties:
                      msg: 
                        type: string
                      info: 
                        type: object
                        properties:
                          id: int
                          username: string
                          name: string
                          password: string
                          role: string
                example: 
                  msg: "Hello, Jeremy (U#13)"
                  info: {
                    "info": {
                      "id": 13,
                      "username": "jeremy6",
                      "name": "Jeremy",
                      "password": "$2b$10$TMBpozM1pGgi6KKHp.hQYeSeODr/gNPbqwb37rzi0ZvOhmRDbiI3.",
                      "role": "user",
                    },
                  }


  /auth/register:
    post:
      tags:
        - auth
      summary: Create an account
      description: > 
        Create one instance of `Users` with request body as its credentials. 
        A token that could be used in the next 30 minutes would be given upon successful authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                username: 
                  type: string
                password: 
                  type: string
              example:
                name: july
                username: july
                password: july
      responses:
        '200':    # status code
          description: A message and a JWT token
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  msg: string
                  authorization: string
              example:
                msg: Account registered. Hello july (U#24)!
                authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzE0Njk0MTU4LCJleHAiOjE3MTQ2OTU5NTh9._wQQOWQi4AEoZP3BpgaoPN8fdYMNd1K1dCA3Mf1eOsQ


  /auth/login:
    post:
      tags:
        - auth
      summary: Login to existing user
      description: >
        Login to existing user to retrieve a JWT token you could use throughout this API. 
        A token that could be used in the next 30 minutes would be given upon successful authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: 
                  type: string
                password: 
                  type: string
              example:
                username: july
                password: july
      responses:
        '200':    # status code
          description: A message and a JWT token
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  msg: string
                  authorization: string
              example:
                msg: Hello july (U#24)!
                authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzE0Njk2ODkxLCJleHAiOjE3MTQ2OTg2OTF9.ollvG0DbNTZK97unyXBmp4XiM9oq-iqWsS40Ennnqag

  # USER ENDPOINT
  /user:
    get:
      tags:
        - Users
      summary: Returns the data of all users.
      description: > 
        Returns all of `Users` data. 
        You need a token and your role must be in `["Superadmin", "Admin"]`
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: A JSON array of Users' data
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data: 
                      type: array
              example: 
                msg: "User data fetch success"
                data: [
                  {
                    "id": 10,
                    "username": "jeremiah",
                    "name": "Jeremiah",
                    "password": "$2a$12$.R3TWIGZI0ZvOSUdW.jtCuv1BLlrTJPjhDR6ZSPZSMS3OxNsfrq16",
                    "role": "admin",
                  },
                  {
                    "id": 11,
                    "username": "jennifer",
                    "name": "Jennifer",
                    "password": "$2a$12$0sKZ8TdJ.qdZ1cfaFFJsIutcWrCAC9RZ/B1BeR3dqLWqubUPiRc7u",
                    "role": "admin",
                  },
                  {
                    "id": 12,
                    "username": "jojon5",
                    "name": "jojon5",
                    "password": "$2b$10$k4px.jl6EylpJyWF4OuU9u4wOfUesp9W.NEvdHWqlf7UER0ku7a8S",
                    "role": "user",
                  },
                ]
    post:
      tags:
        - Users
      summary: Creates an instance of `Users` in database
      description: >
        Creates a record in `Users` with request body as its data. 
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                username: 
                  type: string
                password: 
                  type: string
              example:
                name: july
                username: july
                password: july
      responses:
        '200':    # status code
          description: User data has been successfully inserted to `Users`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "User created with id:26"


  /user/{userId}:
    get:
      tags:
        - Users
      summary: Returns the data of a user
      description: > 
        Returns the data of user with id of `userId`. You need to be logged in to 
        your account. If your role is in `["Superadmin", "Admin"]`, then you can 
        bypass this restriction
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: The id of the existing User
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: User data with id of `userId`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data:
                      type: object
                      properties:
                        id: 
                          type: integer
                        username:
                          type: string
                        name:
                          type: string
                        password: 
                          type: string
                        role: 
                          type: string
              example:  
                msg: "User data fetch success"
                data: {
                  "id": 10,
                  "username": "jeremiah",
                  "name": "Jeremiah",
                  "password": "$2a$12$.R3TWIGZI0ZvOSUdW.jtCuv1BLlrTJPjhDR6ZSPZSMS3OxNsfrq16",
                  "role": "admin",
                }
    put:
      tags:
        - Users
      summary: Edits user data with `id` of `userId`
      description: > 
        Updates user data with `id` of `userId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: The id of the existing User
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                username: 
                  type: string
                password: 
                  type: string
              example:
                name: july
                username: july
                password: july
      responses:
        '200':    # status code
          description: User data has been successfully updated
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Updated user with id: 10"
    delete:
      tags:
        - Users
      summary: Deletes user data with `id` of `userId`
      description: > 
        Deletes user data with `id` of `userId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: The id of the existing User
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: User data has been successfully deleted from `Users`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Deleted user with id: 10"

  # QUIZ ENDPOINT
  /quiz:
    get:
      tags:
        - Quizzes
      summary: Returns the data of all quizzes.
      description: > 
        Returns all of `Quizzes` data. 
        You need a token and your role must be in `["Superadmin", "Admin"]`
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: A JSON array of Quizzes' data
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data: 
                      type: array
              example: 
                msg: "quiz data fetch success"
                data: [
                  {
                    "id": 6,
                    "user_id": 10,
                    "name": "Mathematics",
                    "duration": 15,
                    "visibility": "public",
                  },
                  {
                    "id": 7,
                    "user_id": 11,
                    "name": "Geography",
                    "duration": 10,
                    "visibility": "private",
                  },
                ]
    post:
      tags:
        - Quizzes
      summary: Creates an instance of `Quizzes` in database
      description: >
        Creates a record in `Quizzes` with request body as its data. Note that the propery `duration`
        is on minute unit. That means, `duration: 60` means the duration would be an hour.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                name: 
                  type: string
                duration: 
                  type: integer
                visibility: 
                  type: string
              example:
                user_id: 10
                name: Calculus
                duration: 60
                visibility: private
      responses:
        '200':    # status code
          description: quiz data has been successfully inserted to `Quizzes`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "quiz created with id:26"


  /quiz/{quizId}:
    get:
      tags:
        - Quizzes
      summary: Returns the data of a quiz
      description: > 
        Returns the data of quiz with id of `quizId`. In order to be displayed, the `visibility` of
        the quiz has to be set to `public`. If the `visibility` is `private`, only the owner could
        use this endpoint. If user want to access this, they have to access via `roomQuiz` endpoint by
        providing the appropiate `quiz_id` and `room_id` which requires the owner to assign the quiz
        into a `PrivateRoom`. If your role is in `["Superadmin", "Admin"]`, then you can bypass 
        this restriction
      parameters:
        - in: path
          name: quizId
          type: integer
          required: true
          description: The id of the existing quiz
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: quiz data with id of `quizId`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data:
                      type: object
                      properties:
                        id: 
                          type: integer
                        user_id:
                          type: integer
                        name: 
                          type: string
                        duration: 
                          type: integer
                        visibility: 
                          type: string
              example:  
                msg: "quiz data fetch success"
                data: {
                  "id": 6,
                  "user_id": 10,
                  "name": "Mathematics",
                  "duration": 15,
                  "visibility": "public",
                }
    put:
      tags:
        - Quizzes
      summary: Edits quiz data with `id` of `quizId`
      description: > 
        Updates quiz data with `id` of `quizId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: quizId
          type: integer
          required: true
          description: The id of the existing quiz
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                name: 
                  type: string
                duration: 
                  type: integer
                visibility: 
                  type: string
              example:
                user_id: 10
                name: Calculus
                duration: 60
                visibility: private
      responses:
        '200':    # status code
          description: quiz data has been successfully updated
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Updated quiz with id: 10"
    delete:
      tags:
        - Quizzes
      summary: Deletes quiz data with `id` of `quizId`
      description: > 
        Deletes quiz data with `id` of `quizId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: quizId
          type: integer
          required: true
          description: The id of the existing quiz
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: quiz data has been successfully deleted from `Quizzes`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Deleted quiz with id: 10"

  # QUESTION ENDPOINT
  /question:
    get:
      tags:
        - Questions
      summary: Returns the data of all questions.
      description: > 
        Returns all of `Questions` data. 
        You need a token and your role must be in `["Superadmin", "Admin"]`
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: A JSON array of Questions' data
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data: 
                      type: array
              example: 
                msg: "question data fetch success"
                data: [
                  {
                    "id": 5,
                    "quiz_id": 6,
                    "text": "1 + 1 = ...",
                    "point": 10,
                  },
                  {
                    "id": 6,
                    "quiz_id": 6,
                    "text": "How many sides does a hexagon have?",
                    "point": 5,
                  },
                ]
    post:
      tags:
        - Questions
      summary: Creates an instance of `Questions` in database
      description: >
        Creates a record in `Questions` with request body as its data. Note that the propery `duration`
        is on minute unit. That means, `duration: 60` means the duration would be an hour.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quiz_id:
                  type: integer
                text: 
                  type: string
                point: 
                  type: integer
              example:
                quiz_id: 10
                text: What's the derivative of sin(x)?
                point: 10
      responses:
        '200':    # status code
          description: question data has been successfully inserted to `Questions`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "question created with id:26"


  /question/{questionId}:
    get:
      tags:
        - Questions
      summary: Returns the data of a question
      description: > 
        Returns the data of question with id of `questionId`. In order to be displayed, the `visibility` of
        the question has to be set to `public`. If the `visibility` is `private`, only the owner could
        use this endpoint. If user want to access this, they have to access via `roomquestion` endpoint by
        providing the appropiate `question_id` and `room_id` which requires the owner to assign the question
        into a `PrivateRoom`. If your role is in `["Superadmin", "Admin"]`, then you can bypass 
        this restriction
      parameters:
        - in: path
          name: questionId
          type: integer
          required: true
          description: The id of the existing question
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: question data with id of `questionId`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data:
                      type: object
                      properties:
                        id: 
                          type: integer
                        quiz_id:
                          type: integer
                        text: 
                          type: string
                        point: 
                          type: integer
              example:  
                msg: "question data fetch success"
                data: {
                  "id": 6,
                  "quiz_id": 6,
                  "text": "How many sides does a hexagon have?",
                  "point": 5,
                }
    put:
      tags:
        - Questions
      summary: Edits question data with `id` of `questionId`
      description: > 
        Updates question data with `id` of `questionId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: questionId
          type: integer
          required: true
          description: The id of the existing question
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quiz_id:
                  type: integer
                text: 
                  type: string
                point: 
                  type: integer
              example:
                quiz_id: 10
                text: What's the derivative of sin(x)?
                point: 10
      responses:
        '200':    # status code
          description: question data has been successfully updated
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Updated question with id: 10"
    delete:
      tags:
        - Questions
      summary: Deletes question data with `id` of `questionId`
      description: > 
        Deletes question data with `id` of `questionId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: questionId
          type: integer
          required: true
          description: The id of the existing question
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: question data has been successfully deleted from `Questions`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Deleted question with id: 10"

  # ANSWER ENDPOINT
  /answer:
    get:
      tags:
        - Answers
      summary: Returns the data of all answers.
      description: > 
        Returns all of `Answers` data. Your role must be in `["Superadmin", "Admin"]`
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: A JSON array of `Answers` data
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data: 
                      type: array
              example: 
                msg: "answer data fetch success"
                data: [
                    {
                      "id": 6,
                      "question_id": 5,
                      "text": "2",
                      "isCorrect": 1,
                    },
                    {
                      "id": 7,
                      "question_id": 5,
                      "text": "69",
                      "isCorrect": 0,
                    },
                ]
    post:
      tags:
        - Answers
      summary: Creates an instance of `Answers` in database
      description: >
        Creates a record in `Answers` with request body as its data. Note that the propery `duration`
        is on minute unit. That means, `duration: 60` means the duration would be an hour.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id: 
                  type: integer
                question_id:
                  type: integer
                text: 
                  type: string
                isCorrect: 
                  type: boolean
              example:
                question_id: 10
                text: What's the derivative of sin(x)?
                isCorrect: 10
      responses:
        '200':    # status code
          description: answer data has been successfully inserted to `Answers`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "answer created with id:26"


  /answer/{answerId}:
    get:
      tags:
        - Answers
      summary: Returns the data of a answer
      description: > 
        Returns the data of answer with id of `answerId`
      parameters:
        - in: path
          name: answerId
          type: integer
          required: true
          description: The id of the existing answer
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: answer data with id of `answerId`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data:
                      type: object
                      properties:
                        id: 
                          type: integer
                        question_id:
                          type: integer
                        text: 
                          type: string
                        isCorrect: 
                          type: boolean
              example:  
                msg: "answer data fetch success"
                data: {
                  "id": 6,
                  "question_id": 5,
                  "text": "2",
                  "isCorrect": 1,
                }

    put:
      tags:
        - Answers
      summary: Edits answer data with `id` of `answerId`
      description: > 
        Updates answer data with `id` of `answerId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: answerId
          type: integer
          required: true
          description: The id of the existing answer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question_id:
                  type: integer
                text: 
                  type: string
                isCorrect: 
                  type: boolean
              example:
                question_id: 5
                text: cos(x)
                isCorrect: 1
      responses:
        '200':    # status code
          description: answer data has been successfully updated
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Updated answer with id: 10"
    delete:
      tags:
        - Answers
      summary: Deletes answer data with `id` of `answerId`
      description: > 
        Deletes answer data with `id` of `answerId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: answerId
          type: integer
          required: true
          description: The id of the existing answer
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: answer data has been successfully deleted from `Answers`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Deleted answer with id: 10"

  # ATTEMPT ENDPOINT
  /attempt:
    get:
      tags:
        - Attempts
      summary: Returns the data of all attempts.
      description: > 
        Returns all of `Attempts` data. Your role must be in `["Superadmin", "Admin"]`
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: A JSON array of `Attempts` data
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data: 
                      type: array
              example: 
                msg: "attempt data fetch success"
                data: [
                  {
                    "id": 1,
                    "user_id": 12,
                    "quiz_id": 6,
                    "score": 10,
                  },
                  {
                    "id": 2,
                    "user_id": 13,
                    "quiz_id": 8,
                    "score": 1,
                  },
                ]
    post:
      tags:
        - Attempts
      summary: Creates an instance of `Attempts` in database
      description: >
        Creates a record in `Attempts` with request body as its data. Your role must be
        in `["Superadmin", "Admin"]` to access this.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                quiz_id: 
                  type: integer
                score: 
                  type: integer
              example:
                user_id: 13
                quiz_id: 8
                score: 8
      responses:
        '200':    # status code
          description: attempt data has been successfully inserted to `Attempts`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "attempt created with id:26"


  /attempt/{attemptId}:
    get:
      tags:
        - Attempts
      summary: Returns the data of a attempt
      description: > 
        Returns the data of attempt with id of `attemptId`
      parameters:
        - in: path
          name: attemptId
          type: integer
          required: true
          description: The id of the existing attempt
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: attempt data with id of `attemptId`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data:
                      type: object
                      properties:
                        id: 
                          type: integer
                        user_id:
                          type: integer
                        quiz_id: 
                          type: integer
                        score: 
                          type: integer
              example:  
                msg: "attempt data fetch success"
                data: {
                  "id": 1,
                  "user_id": 12,
                  "quiz_id": 6,
                  "score": 10,
                }

    put:
      tags:
        - Attempts
      summary: Edits attempt data with `id` of `attemptId`
      description: > 
        Updates attempt data with `id` of `attemptId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: attemptId
          type: integer
          required: true
          description: The id of the existing attempt
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  user_id:
                    type: integer
                  quiz_id: 
                    type: integer
                  score: 
                    type: integer
              example:
                user_id: 12
                quiz_id: 6
                score: 10
      responses:
        '200':    # status code
          description: attempt data has been successfully updated
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Updated attempt with id: 10"
    delete:
      tags:
        - Attempts
      summary: Deletes attempt data with `id` of `attemptId`
      description: > 
        Deletes attempt data with `id` of `attemptId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: attemptId
          type: integer
          required: true
          description: The id of the existing attempt
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: attempt data has been successfully deleted from `Attempts`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Deleted attempt with id: 10"

  # Room ENDPOINT
  /room:
    get:
      tags:
        - PrivateRooms
      summary: Returns the data of all rooms.
      description: > 
        Returns all of `PrivateRooms` data. Your role must be in `["Superadmin", "Admin"]`
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: A JSON array of `PrivateRooms` data
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data: 
                      type: array
              example: 
                msg: "room data fetch success"
                data: [
                  {
                    "id": 1,
                    "user_id": 10,
                    "name": "Jeremiah's private room",
                  },
                  {
                    "id": 2,
                    "user_id": 11,
                    "name": "Jennifer's private room",
                  },
                ]
    post:
      tags:
        - PrivateRooms
      summary: Creates an instance of `PrivateRooms` in database
      description: >
        Creates a record in `PrivateRooms` with request body as its data. Your role must be
        in `["Superadmin", "Admin"]` to access this.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                name: 
                  type: string
              example:
                user_id: 10
                name: "Summer class 2024"
      responses:
        '200':    # status code
          description: room data has been successfully inserted to `PrivateRooms`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "room created with id:26"


  /room/{roomId}:
    get:
      tags:
        - PrivateRooms
      summary: Returns the data of a room
      description: > 
        Returns the data of room with id of `roomId`
      parameters:
        - in: path
          name: roomId
          type: integer
          required: true
          description: The id of the existing room
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: room data with id of `roomId`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data:
                      type: object
                      properties:
                        id: 
                          type: integer
                        user_id:
                          type: integer
                        name: 
                          type: string
              example:  
                msg: "room data fetch success"
                data: {
                    "id": 2,
                    "user_id": 11,
                    "name": "Jennifer's private room",
                }
    put:
      tags:
        - PrivateRooms
      summary: Edits room data with `id` of `roomId`
      description: > 
        Updates room data with `id` of `roomId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: roomId
          type: integer
          required: true
          description: The id of the existing room
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                name: 
                  type: string
              example:
                user_id: 10
                name: "Summer class 2024"
      responses:
        '200':    # status code
          description: room data has been successfully updated
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Updated room with id: 10"
    delete:
      tags:
        - PrivateRooms
      summary: Deletes room data with `id` of `roomId`
      description: > 
        Deletes room data with `id` of `roomId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: roomId
          type: integer
          required: true
          description: The id of the existing room
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: room data has been successfully deleted from `PrivateRooms`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Deleted room with id: 10"

  # RoomPermission ENDPOINT
  /roomPermission:
    get:
      tags:
        - RoomPermissions
      summary: Returns the data of all roomPermissions.
      description: > 
        Returns all of `RoomPermissions` data. Your role must be in `["Superadmin", "Admin"]`
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: A JSON array of `RoomPermissions` data
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data: 
                      type: array
              example: 
                msg: "roomPermission data fetch success"
                data: [
                   {
                    "id": 1,
                    "room_id": 1,
                    "user_id": 12,
                  },
                  {
                    "id": 2,
                    "room_id": 1,
                    "user_id": 13,
                  },
                ]
    post:
      tags:
        - RoomPermissions
      summary: Creates an instance of `RoomPermissions` in database
      description: >
        Creates a record in `RoomPermissions` with request body as its data. Your role must be
        in `["Superadmin", "Admin"]` to access this.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                room_id:
                  type: integer
              example:
                user_id: 10
                room_id: 1
      responses:
        '200':    # status code
          description: roomPermission data has been successfully inserted to `RoomPermissions`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "roomPermission created with id:26"


  /roomPermission/{roomPermissionId}:
    get:
      tags:
        - RoomPermissions
      summary: Returns the data of a roomPermission
      description: > 
        Returns the data of roomPermission with id of `roomPermissionId`
      parameters:
        - in: path
          name: roomPermissionId
          type: integer
          required: true
          description: The id of the existing roomPermission
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: roomPermission data with id of `roomPermissionId`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data:
                      type: object
                      properties:
                        id: 
                          type: integer
                        user_id:
                          type: integer
                        room_id:
                          type: integer
              example:  
                msg: "roomPermission data fetch success"
                data: {
                  "id": 1,
                  "room_id": 1,
                  "user_id": 12,
                }
    put:
      tags:
        - RoomPermissions
      summary: Edits roomPermission data with `id` of `roomPermissionId`
      description: > 
        Updates roomPermission data with `id` of `roomPermissionId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: roomPermissionId
          type: integer
          required: true
          description: The id of the existing roomPermission
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                room_id:
                  type: integer
              example:
                room_id: 1
                user_id: 13
      responses:
        '200':    # status code
          description: roomPermission data has been successfully updated
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Updated roomPermission with id: 10"
    delete:
      tags:
        - RoomPermissions
      summary: Deletes roomPermission data with `id` of `roomPermissionId`
      description: > 
        Deletes roomPermission data with `id` of `roomPermissionId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: roomPermissionId
          type: integer
          required: true
          description: The id of the existing roomPermission
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: roomPermission data has been successfully deleted from `RoomPermissions`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Deleted roomPermission with id: 10"

  # RoomQuiz ENDPOINT
  /roomQuiz:
    get:
      tags:
        - RoomQuizzes
      summary: Returns the data of all roomQuizzes.
      description: > 
        Returns all of `RoomQuizzes` data. Your role must be in `["Superadmin", "Admin"]`
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: A JSON array of `RoomQuizzes` data
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data: 
                      type: array
              example: 
                msg: "roomQuiz data fetch success"
                data: [
                 {
                    "id": 6,
                    "room_id": 1,
                    "quiz_id": 6,
                    "user_id": 10,
                    "name": "Mathematics",
                    "duration": 15,
                    "visibility": "public",
                  },
                  {
                    "id": 7,
                    "room_id": 2,
                    "quiz_id": 7,
                    "user_id": 11,
                    "name": "Geography",
                    "duration": 10,
                    "visibility": "private",
                  },
                ]
    post:
      tags:
        - RoomQuizzes
      summary: Creates an instance of `RoomQuizzes` in database
      description: >
        Creates a record in `RoomQuizzes` with request body as its data. Your role must be
        in `["Superadmin", "Admin"]` to access this.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_id:
                  type: integer
                quiz_id:
                  type: integer
              example:
                quiz_id: 11
                room_id: 2
      responses:
        '200':    # status code
          description: roomQuiz data has been successfully inserted to `RoomQuizzes`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "roomQuiz created with id:26"


  /roomQuiz/{roomQuizId}:
    get:
      tags:
        - RoomQuizzes
      summary: Returns the data of a roomQuiz
      description: > 
        Returns the data of roomQuiz with id of `roomQuizId`
      parameters:
        - in: path
          name: roomQuizId
          type: integer
          required: true
          description: The id of the existing roomQuiz
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: roomQuiz data with id of `roomQuizId`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                    data:
                      type: object
                      properties:
                        id: 
                          type: integer
                        room_id:
                          type: integer
                        quiz_id:
                          type: integer
                        user_id:
                          type: integer
                        name:
                          type: string
                        duration:
                          type: integer
                        visibility:
                          type: string
              example:  
                msg: "roomQuiz data fetch success"
                data: {
                  "id": 7,
                  "room_id": 2,
                  "quiz_id": 7,
                  "user_id": 11,
                  "name": "Geography",
                  "duration": 10,
                  "visibility": "private",
                }

    put:
      tags:
        - RoomQuizzes
      summary: Edits roomQuiz data with `id` of `roomQuizId`
      description: > 
        Updates roomQuiz data with `id` of `roomQuizId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: roomQuizId
          type: integer
          required: true
          description: The id of the existing roomQuiz
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_id:
                  type: integer
                quiz_id:
                  type: integer
              example:
                room_id: 1
                quiz_id: 7
      responses:
        '200':    # status code
          description: roomQuiz data has been successfully updated
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Updated roomQuiz with id: 10"
    delete:
      tags:
        - RoomQuizzes
      summary: Deletes roomQuiz data with `id` of `roomQuizId`
      description: > 
        Deletes roomQuiz data with `id` of `roomQuizId`.  Your role must be "Superadmin"
      parameters:
        - in: path
          name: roomQuizId
          type: integer
          required: true
          description: The id of the existing roomQuiz
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: roomQuiz data has been successfully deleted from `RoomQuizzes`
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    msg: 
                      type: string
              example:  
                msg: "Deleted roomQuiz with id: 10"
